package org.firstinspires.ftc.teamcode; // This should match the file location. This is auto generated by Android Studio

import com.pedropathing.math.Pose;
import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;

import com.pedropathing.follower.Follower;

import org.firstinspires.ftc.teamcode.pedro.Constants;

import com.pedropathing.api.PoseFactory;
import com.pedropathing.math.Pose;

import static com.pedropathing.api.Paths.*;
import com.pedropathing.paths.Path;

@Autonomous
public class AutoTest extends OpMode {

    private Follower follower;




    private final PoseFactory p = PoseFactory.degrees(); // the factory we added before, we are still at the top of the class

    private final Pose startPose = p.of(24, 24, 0);
    private final Pose park = p.of(48, 48, 90);

    private Path park() {
        return line(startPose, park).linear(startPose, park);
    }

    //private final Pose startPose = new Pose(0,0,0);
    private final Pose movePose = new Pose(10,10,Math.PI/2);
    private final Pose endPose = new Pose(20,10,Math.PI/4);

    //driveStartPosShootPos = follower.pathBuilder().addPath(new BezierLine(startPose, shootPose)).setLinearHeadingInterpolation(startPose.getHeading(), shootPose.getHeading()).build();

    @Override
    public void init() {
        follower = Constants.create(hardwareMap);
        follower.setPose(startPose);

    }
    @Override
    public void start() {

    }

    @Override
    public void loop() {

    }
}